version: '3'

services:
  nodejs:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_HOSTNAME: mongo_db
      MONGO_PORT: 27017
      MONGO_DB: my_db
      APP_PORT: 5000
      MONGO_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo
    restart: always
    volumes: 
      - mongo_db:/data/db

# networks:
#   my-network:

volumes:
  mongo_db: {}